#!/usr/bin/env node
// Build dist/: one self-contained paste file per craft domain (PROMPT.md merged with the
// craft standard, task slot last), so chat-surface users paste one file instead of
// finding and attaching the right craft file themselves.
//
//   node scripts/build-dist.mjs          # writes dist/frontier-<domain>.md
//   node scripts/build-dist.mjs --check  # exits 1 if dist/ is stale (CI)

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const craftDir = join(root, "frontier", "references", "craft");
const distDir = join(root, "dist");
const check = process.argv.includes("--check");

const PASTE_LINE = "PASTE YOUR TASK AND INPUTS BELOW THIS LINE.";
const prompt = readFileSync(join(root, "PROMPT.md"), "utf8");

// Keep the body between the intro separator and the paste line; the merged file carries
// its own intro and puts the paste line after the craft standard.
const sepIdx = prompt.indexOf("\n---\n");
const pasteIdx = prompt.indexOf(PASTE_LINE);
if (sepIdx === -1 || pasteIdx === -1) {
  console.error("PROMPT.md shape changed: separator or paste line not found");
  process.exit(1);
}
const body = prompt.slice(sepIdx + 5, pasteIdx).trimEnd();

let stale = [];
if (!check) mkdirSync(distDir, { recursive: true });

for (const file of readdirSync(craftDir).filter((f) => f.endsWith(".md")).sort()) {
  const domain = basename(file, ".md");
  const craft = readFileSync(join(craftDir, file), "utf8").trimEnd();
  const out = `# Frontier: ${domain} (single paste file)

Generated by scripts/build-dist.mjs from PROMPT.md + frontier/references/craft/${file};
edit those sources, not this file. Paste this whole file into any capable agent and put
your task and inputs LAST, below everything.

---

${body}

CRAFT STANDARD (${domain}); this is the rubric base the laws above refer to:

${craft}

${PASTE_LINE}
`;
  const target = join(distDir, `frontier-${domain}.md`);
  if (check) {
    const current = existsSync(target) ? readFileSync(target, "utf8") : null;
    if (current !== out) stale.push(target);
  } else {
    writeFileSync(target, out);
    console.log("wrote", target);
  }
}

if (check && stale.length) {
  console.error("dist/ is stale; run: node scripts/build-dist.mjs\n" + stale.join("\n"));
  process.exit(1);
}
